import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { focusHome, buildWawasan } from './build-wawasan.mjs';
const origin='https://notaris-biondy-utama-cimahi.biondy31.chatgpt.site';
const articles=[
  {slug:'persiapan-pendirian-pt',category:'PERSEROAN',title:'Persiapan pendirian PT sebelum bertemu notaris',intro:'Beberapa bahan pembahasan awal agar rencana pendirian perseroan dapat dijelaskan dengan lebih terarah.',content:`
<h2>Mulai dari rencana usahanya</h2><p>Tuliskan kegiatan yang benar-benar ingin dijalankan, rencana lokasi, dan siapa yang terlibat. Cerita singkat tentang usaha lebih membantu pembahasan awal daripada sekadar memilih nama dokumen yang ingin dibuat.</p>
<h2>Siapkan bahan pembahasan</h2><ul><li>Pilihan nama perseroan serta tempat kedudukannya.</li><li>Uraian kegiatan usaha yang direncanakan.</li><li>Identitas calon pendiri dan rencana susunan pengurus.</li><li>Rencana modal dan pembagian kepemilikan saham.</li><li>Alamat serta keterangan tempat kegiatan usaha.</li></ul><p>Nama, kedudukan, kegiatan, modal, serta pengurus juga menjadi bagian informasi dalam panduan pendirian perseroan pada AHU. Bawa rencana yang sudah Anda miliki untuk dibahas; tidak perlu menganggap seluruh pilihannya sudah final.</p>
<h2>Tanyakan hal yang belum jelas</h2><p>Diskusikan kesesuaian bentuk badan usaha dengan rencana Anda, dokumen pendukung, tahapan pekerjaan, dan rincian biaya. Jika sudah ada usaha atau kesepakatan sebelumnya, ceritakan sejak awal agar konteksnya dapat diperiksa.</p><p>Untuk membahas kebutuhan pendirian PT di Kota Cimahi, hubungi Kantor Notaris Biondy Utama dan konfirmasikan jadwal serta dokumen awal yang perlu dibawa.</p>`,sources:[['Panduan pendirian perseroan — AHU','https://panduan.ahu.go.id/doku.php?id=pendirian_perseroan']]},
  {slug:'persiapan-jual-beli-tanah',category:'PERTANAHAN',title:'Persiapan awal jual beli tanah di Cimahi',intro:'Kenali informasi yang perlu dibahas mengenai para pihak, objek tanah, dan rencana transaksi sebelum menyiapkan akta.',content:`
<h2>Kenali objek dan dokumen yang dimiliki</h2><p>Catat lokasi tanah, nama yang tercantum pada dokumen kepemilikan, serta dokumen yang sudah tersedia. Siapkan sertipikat dan dokumen pendukung untuk dibahas, lalu konfirmasikan kepada kantor dokumen asli yang perlu dibawa.</p><h2>Ceritakan kondisi transaksi</h2><ul><li>Siapa penjual dan pembeli, serta apakah bertindak sendiri atau mewakili pihak lain.</li><li>Apakah ada pembiayaan bank atau kewajiban yang berkaitan dengan objek.</li><li>Bagaimana kondisi penguasaan tanah dan bangunannya.</li><li>Apakah ada perbedaan data atau dokumen yang belum tersedia.</li><li>Apa yang sudah disepakati para pihak dan apa yang masih perlu dibahas.</li></ul><p>Informasi tersebut membantu mengarahkan pemeriksaan awal. Jangan menyimpulkan kesiapan transaksi hanya dari daftar umum atau foto satu dokumen.</p><h2>Bahas pemeriksaan dan tahap berikutnya</h2><p>Tanyakan dokumen pendukung, pemeriksaan objek, komponen biaya, serta urutan proses yang sesuai dengan kondisi transaksi. Kementerian ATR/BPN memiliki petunjuk teknis tersendiri mengenai layanan pengecekan sertipikat dan SKPT elektronik; penerapannya pada objek Anda perlu dibahas dengan petugas yang menangani.</p><p>Untuk kebutuhan Akta Jual Beli dan balik nama di Kota Cimahi, hubungi kantor agar lokasi objek dan kondisi para pihak dapat dibicarakan terlebih dahulu.</p>`,sources:[['Layanan pengecekan sertipikat dan SKPT elektronik — JDIH ATR/BPN','https://jdih.atrbpn.go.id/peraturan/detail/1066/petunjuk-teknis-nomor-3-juknis-hk-02-iv-2022-tahun-2022']]},
  {slug:'sebelum-ke-notaris',category:'KUNJUNGAN KANTOR',title:'Pertemuan pertama dengan notaris: mulai dari mana?',intro:'Anda tidak perlu sudah mengetahui nama akta yang tepat. Mulailah dengan kebutuhan yang ingin dibahas.',content:`
<h2>Siapkan cerita singkat</h2><p>Jelaskan apa yang ingin dilakukan, siapa saja yang terlibat, dan hasil yang diharapkan. Misalnya, hendak mendirikan usaha, mengubah pengurus perseroan, atau membahas dokumen untuk transaksi tanah.</p><h2>Kumpulkan dokumen yang sudah ada</h2><p>Susun dokumen sesuai urutannya dan tandai bagian yang ingin ditanyakan. Jika ada akta terdahulu, perubahan data, atau kesepakatan yang sudah dibuat, sampaikan keberadaannya kepada kantor.</p><p>Hubungi kantor terlebih dahulu untuk memastikan dokumen yang perlu dibawa. Hindari mengirim dokumen pribadi ke kontak yang belum Anda pastikan.</p><h2>Catat pertanyaan penting</h2><ul><li>Apa ruang lingkup pekerjaan yang diperlukan?</li><li>Dokumen apa yang masih perlu dilengkapi?</li><li>Siapa yang perlu hadir dan pada tahapan apa?</li><li>Apa komponen biaya yang perlu dipahami?</li><li>Bagaimana tahapan dan perkiraan waktu pengerjaannya?</li></ul><h2>Konfirmasikan waktu kunjungan</h2><p>Kantor Biondy Utama berada di Perumahan Taman Mutiara, Karangmekar, Cimahi Tengah. Gunakan nomor telepon yang tercantum pada halaman kontak untuk membahas waktu kunjungan dan persiapan pertemuan.</p>`,sources:[]}
];
let home=focusHome(await readFile('./index.html','utf8'));
const header=home.match(/<div class="topline">[\s\S]*?<\/header>/)[0].replaceAll('href="#','href="/#');
const footer=home.match(/<footer[\s\S]*?<\/footer>/)[0].replaceAll('href="#','href="/#');
const icon=home.match(/<link rel="icon"[^>]+>/)[0];
for(const article of articles){
 const url=origin+'/panduan/'+article.slug+'/';
 const schema={'@context':'https://schema.org','@type':'Article',headline:article.title,description:article.intro,inLanguage:'id-ID',mainEntityOfPage:url,publisher:{'@type':'Organization',name:'Kantor Notaris & PPAT Biondy Utama'}};
 const page=`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${article.title} | Biondy Utama, Cimahi</title><meta name="description" content="${article.intro}"><meta name="theme-color" content="#143d32"><link rel="canonical" href="${url}"><meta property="og:type" content="article"><meta property="og:locale" content="id_ID"><meta property="og:title" content="${article.title}"><meta property="og:description" content="${article.intro}"><meta property="og:url" content="${url}">${icon}<link rel="stylesheet" href="/assets/style.css"><script type="application/ld+json">${JSON.stringify(schema)}</script></head><body><a class="skip" href="#utama">Lewati ke isi utama</a>${header}<main id="utama"><section class="article-banner"><div class="container"><nav class="breadcrumbs" aria-label="Jejak navigasi"><a href="/">Beranda</a><span>/</span><a href="/#panduan">Panduan</a></nav><p class="eyebrow">${article.category}</p><h1>${article.title}</h1><p>${article.intro}</p></div></section><div class="container article-layout"><article class="article-body">${article.content}<p class="article-note">Panduan ini merupakan informasi awal, bukan daftar persyaratan lengkap atau penilaian atas dokumen tertentu. Persiapan disesuaikan setelah pembahasan kondisi Anda.</p>${article.sources.length?'<div class="source-links">Rujukan informasi'+article.sources.map(([name,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${name} ↗</a>`).join('')+'</div>':''}</article><aside class="article-aside"><p class="eyebrow">BIONDY UTAMA · KOTA CIMAHI</p><h2>Ingin membahas kebutuhan Anda?</h2><p>Hubungi kantor untuk menjelaskan rencana dan mengonfirmasi waktu kunjungan.</p><a class="button primary" href="tel:+62816663149">Telepon 0816 663 149</a><a class="button outline" href="/#kontak">Lihat lokasi kantor</a></aside></div></main>${footer}<script src="/assets/app.js" defer></script></body></html>`;
 await mkdir('./panduan/'+article.slug,{recursive:true});
 await writeFile('./panduan/'+article.slug+'/index.html',page);
}
const schema={'@context':'https://schema.org','@type':'LegalService',name:'Kantor Notaris & PPAT Biondy Utama, S.H., M.Kn.',url:origin+'/',telephone:'+62816663149',address:{'@type':'PostalAddress',streetAddress:'Jl. Taman Mutiara Raya, Perumahan Taman Mutiara Blok D2 No. 36, Karangmekar, Cimahi Tengah',addressLocality:'Kota Cimahi',addressRegion:'Jawa Barat',postalCode:'40522',addressCountry:'ID'},sameAs:['https://share.google/tJf8WvjuAEufzdTzH']};
home=home.replace(/<!-- SEO-AWAL -->[\s\S]*?<!-- SEO-AKHIR -->\n?/g,'');
home=home.replace('</head>',`<!-- SEO-AWAL --><link rel="canonical" href="${origin}/"><meta property="og:url" content="${origin}/"><script type="application/ld+json">${JSON.stringify(schema)}</script><!-- SEO-AKHIR -->\n</head>`);
await writeFile('./index.html',home);
const knowledgePaths=await buildWawasan(home,origin);
await writeFile('./sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/',...articles.map(a=>'/panduan/'+a.slug+'/'),...knowledgePaths].map(path=>`<url><loc>${origin+path}</loc></url>`).join('')}</urlset>`);
await writeFile('./robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
console.log('Beranda, tiga panduan, koleksi dan 20 artikel badan usaha beserta sitemap telah dibuat.');
