// Kasus rekaan untuk edukasi; tidak bersumber dari identitas atau berkas klien.
const s = (heading, body, refs = []) => ({ heading, paragraphs: body.split('\n\n'), refs });
export const sources = {
  upt: { title: 'UU 40/2007 tentang Perseroan Terbatas — dibaca bersama perubahan dalam UU 6/2023', url: 'https://www.pajak.go.id/id/peraturan/perseroan-terbatas-0' },
  cipta: { title: 'UU 6/2023 tentang penetapan Perppu Cipta Kerja — perubahan UUPT dalam Pasal 109 lampiran', url: 'https://peraturan.go.id/id/uu-no-6-tahun-2023' },
  modal: { title: 'PP 8/2021 — modal dan perseroan perorangan', url: 'https://jdih.kppu.go.id/common/dokumen/2021pp008.pdf' },
  pt: { title: 'Permenkum 49/2025 — pendirian, perubahan, pembubaran, dan laporan tahunan PT', url: 'https://www.peraturan.go.id/files/permenkum-no-49-tahun-2025.pdf' },
  cv: { title: 'Permenkum 25/2025 — layanan persekutuan perdata, firma, dan CV', url: 'https://www.peraturan.go.id/files/permenkum-no-25-tahun-2025.pdf' },
  dagang: { title: 'KUHD — khususnya Pasal 19–21 tentang persekutuan komanditer', url: 'https://jdih.mahkamahagung.go.id/legal-product/kitab-undang-undang-hukum-dagang/download/dokumen' },
  perdata: { title: 'KUHPerdata — ketentuan persekutuan, termasuk Pasal 1646 dan 1651', url: 'https://jdih.mahkamahagung.go.id/legal-product/kitab-undang-undang-hukum-perdata/download/dokumen' },
  izin: { title: 'PP 28/2025 tentang Perizinan Berusaha Berbasis Risiko', url: 'https://peraturan.go.id/id/pp-no-28-tahun-2025' },
  kbli: { title: 'BPS, 27 April 2026 — implementasi KBLI 2025 dan penyesuaian perizinan', url: 'https://www.bps.go.id/id/news/2026/04/27/898/pemerintah-memastikan-kbli-2025-tidak-memerlukan-perizinan-baru.html' },
  alihcv: { title: 'FAQ AHU — pendirian PT dari usaha yang sebelumnya dijalankan sebagai CV', url: 'https://portal.ahu.go.id/page/faq' }
};

export const articles = [
  {
    slug: 'memilih-pt-atau-cv', type: 'PT & CV', group: 'Memulai usaha', title: 'PT atau CV: mulai dari cara Anda bekerja bersama',
    intro: 'Dua rekan ingin membuka usaha. Pilihan bentuk usahanya perlu mengikuti pembagian peran, risiko, dan rencana kepemilikan.',
    scenario: 'Dua rekan merintis usaha perlengkapan rumah. Seorang menangani pembelian dan pelanggan; seorang lagi menyediakan modal, tetapi ingin ikut menandatangani kontrak. Mereka tertarik pada CV karena terdengar sederhana. Dalam dua tahun, mereka juga berencana menerima investor baru.',
    sections: [
      s('Pertanyaan pertama: siapa yang mengurus?', 'Dalam CV terdapat sekutu komplementer yang mengurus dan bertanggung jawab secara pribadi secara tanggung renteng, serta sekutu komanditer dengan batas peran tertentu. Larangan pengurusan oleh sekutu komanditer dan akibat pelanggarannya diatur dalam Pasal 20–21 KUHD. Menyebut seseorang sebagai investor pasif tidak cukup apabila praktiknya ia justru menjalankan pengurusan.\n\nPT mempunyai susunan kepemilikan dalam saham dan organ berupa RUPS, Direksi, serta Dewan Komisaris. Pada prinsipnya tanggung jawab pemegang saham terbatas, tetapi Pasal 3 UUPT juga memuat pengecualian. Bentuk PT bukan jaminan bahwa semua perbuatan pribadi pemilik bebas dari tanggung jawab.', ['dagang', 'upt']),
      s('Uji pilihan terhadap rencana dua tahun ke depan', 'Untuk kasus tersebut, calon pendiri perlu menjelaskan apakah keduanya ingin aktif mengurus, bagaimana keputusan penting diambil, dan bagaimana pihak baru dapat masuk. Rencana menerima investor membuat pembagian saham, hak suara, serta perubahan komposisi kepemilikan menjadi bahan pembahasan penting.\n\nBandingkan juga kebutuhan pelanggan atau mitra. Jika suatu kerja sama mensyaratkan bentuk badan tertentu, minta dokumen persyaratannya. Jangan mengandalkan cerita bahwa semua tender menerima CV atau bahwa setiap usaha harus berbentuk PT. Persyaratan kegiatan, kontrak, dan perizinan dapat berbeda.'),
      s('Akta dan izin menjawab pertanyaan yang berbeda', 'Pendirian mengatur wadah dan hubungan para pihak. Legalitas menjalankan kegiatan usaha juga memerlukan pemeriksaan perizinan sesuai kegiatan dan tingkat risikonya. Akta yang selesai tidak otomatis menjawab seluruh kebutuhan izin operasional.\n\nHasil pembicaraan yang baik adalah pilihan yang dapat dijelaskan: siapa pemiliknya, siapa pengurusnya, bagaimana risikonya, dan apa yang perlu dilakukan ketika usaha berubah. Keputusan itu lebih berguna daripada memilih hanya berdasarkan nama bentuk usaha atau biaya awal.', ['izin'])
    ],
    checklist: ['Uraian usaha dan lokasi kegiatan yang benar-benar direncanakan.', 'Peran setiap pendiri: menyediakan modal, mengurus, atau keduanya.', 'Rencana menerima investor, pinjaman, dan persyaratan calon mitra.'],
    takeaway: 'Bawalah rencana kerja sama terlebih dahulu. Bentuk usaha dapat dibahas setelah hubungan para pendirinya jelas.',
    related: ['sekutu-aktif-pasif-cv', 'pendirian-pt-pembagian-peran'], repo: ['docs/form-akta/FORM-pendirian-pt.md', 'docs/form-akta/FORM-pendirian-cv.md']
  },
  {
    slug: 'pendirian-pt-pembagian-peran', type: 'PT', group: 'Memulai usaha', title: 'Mendirikan PT bersama teman: sepakati lebih dari nama perusahaan',
    intro: 'Pembagian saham, pekerjaan sehari-hari, dan kewenangan menandatangani perlu dibicarakan sebagai tiga hal yang berbeda.',
    scenario: 'Tiga teman membangun studio desain. Mereka sepakat memakai nama yang sama dan membagi saham sama rata. Namun hanya satu orang akan bekerja penuh waktu. Dua lainnya menganggap seluruh pengeluaran tetap harus mendapat persetujuan bersama, termasuk pembelian alat kerja kecil.',
    sections: [
      s('Pemegang saham tidak otomatis menjadi pengurus', 'Kepemilikan memberi hak sebagai pemegang saham sesuai undang-undang dan anggaran dasar. Pengurusan serta perwakilan perseroan merupakan fungsi Direksi, sedangkan Dewan Komisaris menjalankan pengawasan dan memberi nasihat. Ketiganya perlu dibedakan ketika menyusun kesepakatan para pendiri.\n\nDalam contoh ini, kepemilikan yang seimbang belum menjelaskan siapa boleh menandatangani kontrak pelanggan atau mengangkat pekerja. UUPT menempatkan kewenangan organ dalam batas undang-undang dan anggaran dasar. Keputusan operasional tidak dapat begitu saja disamakan dengan keputusan pemegang saham.', ['upt']),
      s('Bicarakan uang, waktu, dan keputusan', 'Daftarkan kontribusi yang akan diberikan: setoran modal, peralatan, pekerjaan, atau hubungan dengan pelanggan. Janji bekerja penuh waktu tidak boleh langsung dicatat seolah-olah merupakan setoran modal tunai yang telah dibayar. Bentuk kontribusi dan akibatnya perlu dinilai serta didokumentasikan sesuai sifatnya.\n\nPendiri juga dapat membahas anggaran kerja, pelaporan kepada pemilik, penghasilan pengurus, dan keputusan yang membutuhkan persetujuan tertentu. Hindari kesepakatan yang membuat semua tindakan kecil memerlukan rapat, tetapi jangan menyerahkan transaksi besar tanpa batas. Rumusan dalam perjanjian pendiri perlu diselaraskan dengan anggaran dasar dan kewenangan organ. Kesepakatan privat tidak boleh diasumsikan mengalahkan hukum atau otomatis mengikat pihak ketiga.'),
      s('Siapkan keadaan ketika rencana berubah', 'Hubungan yang baik di awal membantu pembicaraan tentang masa depan: bagaimana jika seorang pendiri berhenti bekerja, ingin menjual saham, atau tidak memenuhi kontribusinya? Berhenti bekerja tidak otomatis menghapus saham seseorang. Jabatan, hubungan kerja, dan kepemilikan mempunyai dasar masing-masing.\n\nPendirian PT persekutuan modal mengikuti ketentuan pendirian dan pendaftaran yang berlaku. Perseroan perorangan memiliki jalur tersendiri untuk kriteria tertentu; jangan mencampurkan kedua bentuk itu hanya karena satu orang paling aktif menjalankan usaha.', ['cipta', 'pt'])
    ], checklist: ['Rencana komposisi saham dan bukti kemampuan memenuhi setoran.', 'Calon Direksi dan Komisaris serta pembagian tanggung jawab.', 'Daftar keputusan penting dan skenario jika salah satu pendiri keluar.'],
    takeaway: 'Pertemuan pendirian akan lebih terarah jika para pendiri membawa kesepakatan yang sudah dibahas dan bagian yang masih berbeda pendapat.',
    related: ['modal-dasar-ditempatkan-disetor', 'saham-sama-rata-kebuntuan'], repo: ['docs/form-akta/FORM-pendirian-pt.md', 'utils/pendirianValidator.js']
  },
  {
    slug: 'modal-dasar-ditempatkan-disetor', type: 'PT', group: 'Memulai usaha', title: 'Modal PT: bedakan angka dalam akta dengan setoran yang nyata',
    intro: 'Modal dasar, modal ditempatkan, dan modal disetor saling berkaitan, tetapi tidak berarti hal yang sama.',
    scenario: 'Para pendiri ingin mencantumkan modal dasar Rp1 miliar agar tampak siap menerima proyek besar. Dana yang tersedia baru Rp100 juta. Mereka mengira kekurangannya dapat dianggap lunas karena perusahaan diperkirakan memperoleh pendapatan setelah beroperasi.',
    sections: [
      s('Tiga istilah yang perlu dibaca bersama', 'Modal dasar menggambarkan keseluruhan nilai nominal saham yang ditetapkan dalam anggaran dasar. Modal ditempatkan menunjukkan bagian yang diambil oleh pemegang saham. Modal disetor berkaitan dengan pemenuhan setoran atas bagian tersebut. Pendapatan yang masih diharapkan bukan bukti setoran yang sudah dilakukan.\n\nPP 8/2021 menyatakan besaran modal dasar ditentukan oleh pendiri, dengan sedikitnya 25 persen ditempatkan dan disetor penuh serta dibuktikan dengan bukti penyetoran yang sah. Kegiatan tertentu dapat mempunyai ketentuan modal khusus. Karena itu kebebasan menentukan modal dasar tidak berarti bebas mencantumkan setoran yang belum ada.', ['modal']),
      s('Baca contoh angkanya tanpa mencampur kategori', 'Jika modal dasar dipilih Rp1 miliar, 25 persennya adalah Rp250 juta. Dana Rp100 juta belum memenuhi angka itu. Para pendiri perlu menilai kembali pilihan modal dasar, kesiapan setoran, dan ketentuan kegiatan usahanya; bukan mengisi kekurangan dengan proyeksi penjualan.\n\nJumlah lembar saham dikalikan nilai nominal harus sejalan dengan nilai modal yang ditempatkan. Misalnya 250 lembar dengan nominal Rp1 juta menghasilkan Rp250 juta. Harga yang kelak dibayar investor untuk saham dapat berbeda dari nominal. Perbedaan harga tersebut tidak boleh membuat jumlah saham atau setoran dalam dokumen menjadi tidak konsisten.'),
      s('Jika kontribusinya bukan uang', 'Setoran dalam bentuk selain uang memerlukan pembahasan tersendiri mengenai objek, kepemilikan, penilaian, dan cara penyerahannya. Pasal 34 UUPT mengatur penyetoran modal dalam bentuk lain beserta dasar penilaiannya. Tidak semua janji, jasa mendatang, atau barang yang dipakai usaha otomatis menjadi setoran saham yang sah.\n\nBukti setoran dan catatan keuangan perlu dipelihara setelah pendirian. Jika pemilik kemudian memberikan dana tambahan, tentukan apakah itu pinjaman, setoran untuk penerbitan saham, atau bentuk lain. Satu transfer tidak menjawab sendiri status hukumnya.', ['upt'])
    ], checklist: ['Rencana modal dasar, nilai nominal, dan lembar saham setiap pendiri.', 'Bukti penyetoran dan asal kepemilikan barang jika ada setoran nonuang.', 'Persyaratan modal khusus dari kegiatan usaha yang dituju.'],
    takeaway: 'Angka modal sebaiknya dapat ditelusuri ke keputusan, perhitungan saham, dan bukti pemenuhannya.',
    related: ['investor-baru-dilusi-saham', 'pendirian-pt-pembagian-peran'], repo: ['utils/pendirianValidator.js', 'utils/peroranganKePtBiasaValidator.js']
  },
  {
    slug: 'pt-perorangan-masuk-investor', type: 'PT', group: 'Memulai usaha', title: 'PT perorangan menerima investor: kapan statusnya perlu berubah?',
    intro: 'Masuknya pemegang saham kedua berbeda dari pemberian pinjaman. Tentukan dulu hubungan yang benar-benar disepakati.',
    scenario: 'Pemilik usaha makanan mendirikan perseroan perorangan. Seorang rekan menawarkan Rp200 juta dan meminta 30 persen kepemilikan. Pemilik ingin cukup menambahkan nama rekannya pada catatan internal, sementara dokumen perseroan tetap atas satu orang.',
    sections: [
      s('Masuk sebagai pemilik atau sebagai pemberi pinjaman?', 'Istilah investor sering dipakai untuk dua hubungan yang berbeda. Pemberi pinjaman mempunyai tagihan sesuai perjanjiannya; pemegang saham memperoleh bagian kepemilikan dengan hak dan risiko yang berbeda. Janji memperoleh bagian laba juga perlu dibaca dari isi perjanjian, bukan hanya namanya.\n\nJika pihak kedua benar-benar masuk sebagai pemegang saham, status perseroan perorangan perlu diperhatikan. Pasal 9 PP 8/2021 dan Pasal 25 Permenkum 49/2025 mengatur perubahan status ketika pemegang saham menjadi lebih dari satu orang dan/atau perseroan tidak lagi memenuhi kriteria usaha mikro dan kecil. Perubahan dilakukan melalui akta notaris dan pendaftaran elektronik.', ['modal', 'pt']),
      s('Tentukan saham yang diperoleh investor', 'Ada perbedaan antara investor membeli sebagian saham pemilik lama dan mengambil saham baru melalui penambahan modal. Pada pembelian saham lama, pembayaran pada prinsipnya merupakan harga kepada penjual. Pada setoran saham baru, dana menjadi setoran kepada perseroan. Kedua alur ini menghasilkan catatan dan konsekuensi yang berbeda.\n\nMisalnya pemilik mempunyai 100 lembar saham. Menjual 30 lembar menghasilkan kepemilikan 30 persen bagi pembeli tanpa menambah total lembar. Menerbitkan 30 lembar baru membuat kepemilikan investor menjadi 30 dari 130 lembar, bukan 30 persen. Persentase yang diinginkan perlu dihitung sebelum nominal disepakati.'),
      s('Jaga kesinambungan dokumen usaha', 'Siapkan pernyataan pendirian, dokumen pendaftaran, perubahan yang pernah dilakukan, serta data modal dan kegiatan usaha. Dokumen perubahan perlu menerangkan perseroan mana yang berubah status dan susunan setelah perubahan; bukan sekadar memulai cerita baru tanpa riwayat.\n\nPerubahan status juga menjadi saat yang tepat untuk membahas Direksi, Komisaris, keputusan pemegang saham, serta pembaruan data bank dan perizinan yang relevan. Jadwal transaksi sebaiknya memberi waktu untuk tahapan tersebut sebelum investor menganggap seluruh haknya sudah berlaku.', ['pt'])
    ], checklist: ['Dokumen pendirian dan pendaftaran perseroan perorangan beserta perubahannya.', 'Kesepakatan apakah uang masuk melalui pembelian saham atau setoran modal.', 'Tabel lembar saham sebelum dan sesudah transaksi serta rencana pengurus.'],
    takeaway: 'Ceritakan mekanisme masuknya dana saat berkonsultasi. Besar nominal saja belum menunjukkan bentuk perubahan yang diperlukan.',
    related: ['investor-baru-dilusi-saham', 'jual-beli-saham-pengambilalihan'], repo: ['utils/peroranganKePtBiasaValidator.js', 'utils/peroranganKePtBiasaNormalisasi.js']
  },
  {
    slug: 'saham-sama-rata-kebuntuan', type: 'PT', group: 'Menata keputusan', title: 'Saham 50:50: bagaimana jika dua pendiri berbeda arah?',
    intro: 'Pembagian sama rata dapat terasa adil, tetapi perlu dilengkapi cara mengambil keputusan dan menghadapi kebuntuan.',
    scenario: 'Dua pendiri masing-masing memiliki separuh saham perusahaan jasa. Seorang ingin menggunakan laba untuk membuka cabang, seorang ingin membagikannya. Keduanya merasa berhak menentukan arah. Pertemuan berulang tidak menghasilkan kesepakatan, sementara keputusan operasional ikut tertunda.',
    sections: [
      s('Pisahkan kebuntuan pemilik dari pekerjaan Direksi', 'Tidak semua perbedaan pendapat harus diputus oleh pemegang saham. Identifikasi dahulu apakah persoalannya berada dalam kewenangan Direksi, memerlukan persetujuan Komisaris menurut anggaran dasar, atau memang menjadi kewenangan RUPS. Pembagian fungsi ini membantu mencegah setiap masalah operasional berubah menjadi sengketa kepemilikan.\n\nPasal 87 UUPT mengutamakan musyawarah dan mengatur pengambilan keputusan ketika mufakat tidak tercapai. Kuorum kehadiran dan jumlah suara setuju harus diperiksa berdasarkan agenda, undang-undang, serta anggaran dasar. Tidak tepat menyimpulkan bahwa setiap keputusan cukup dengan suara satu pemilik karena ia sudah hadir sendiri.', ['upt']),
      s('Rancang cara menyelesaikan perbedaan sebelum terjadi', 'Para pendiri dapat membahas urutan perundingan, bantuan mediator, batas waktu pembahasan, atau mekanisme keluar yang wajar jika kebuntuan terus berlangsung. Rumusan tersebut perlu diuji terhadap hak para pihak, aturan pemindahan saham, serta kemampuan pembiayaan masing-masing.\n\nKlausul pembelian saham paksa atau hak membeli lebih dahulu tidak sebaiknya ditempel dari contoh tanpa memahami cara kerjanya. Bagaimana harga ditentukan? Siapa yang menilai? Apa yang terjadi jika pihak yang harus membeli tidak mempunyai dana? Pertanyaan ini perlu dijawab agar klausul dapat dijalankan, bukan hanya terlihat lengkap.'),
      s('Ketika kebuntuan sudah terjadi', 'Susun catatan agenda yang belum disepakati, undangan rapat, risalah, serta korespondensi yang relevan. Bedakan fakta yang disepakati dari penilaian masing-masing pihak. Notaris memerlukan dasar keputusan yang sah untuk menuangkannya ke dalam akta; akta tidak menggantikan persetujuan yang belum tercapai.\n\nKeputusan sirkuler juga bukan jalan pintas mengatasi satu pemilik yang menolak. Pasal 91 UUPT mensyaratkan persetujuan tertulis seluruh pemegang saham dengan hak suara. Apabila sengketa telah memerlukan pendampingan atau proses penyelesaian sengketa, ruang lingkup bantuan itu perlu dibahas tersendiri.', ['upt'])
    ], checklist: ['Anggaran dasar terbaru dan perjanjian antarpemegang saham bila ada.', 'Agenda yang buntu serta catatan keputusan atau rapat sebelumnya.', 'Pilihan yang masih dapat diterima kedua pihak, termasuk keberlanjutan operasional.'],
    takeaway: 'Kepemilikan seimbang akan lebih berguna jika disertai batas kewenangan dan cara menyelesaikan perbedaan yang jelas.',
    related: ['rups-dan-keputusan-sirkuler', 'jual-beli-saham-pengambilalihan'], repo: ['utils/sirkulerValidator.js', 'utils/penggabungan/kuorum.js']
  }
];

articles.push(
  {
    slug: 'penggabungan-dua-pt', type: 'PT', group: 'Menjaga kesinambungan', title: 'Menggabungkan dua PT: lebih dari menyatukan kegiatan operasional',
    intro: 'Penggabungan perlu memetakan aset, kewajiban, saham, dan kepentingan pihak yang terpengaruh.',
    scenario: 'Satu keluarga memiliki dua PT dengan kegiatan saling melengkapi. Mereka ingin memakai satu perusahaan saja agar administrasi lebih sederhana. Rencana awal hanya mengganti nama pada faktur, padahal kedua PT mempunyai kreditor, pekerja, kontrak, dan susunan pemegang saham yang berbeda.',
    sections: [
      s('Tentukan peristiwa hukum yang dimaksud', 'Penggabungan menurut UUPT adalah masuknya satu atau lebih perseroan ke dalam perseroan lain yang sudah ada. Aktiva dan pasiva beralih karena hukum, sedangkan status badan hukum perseroan yang menggabungkan diri berakhir. Ini berbeda dari peleburan yang membentuk perseroan baru, atau jual beli aset tertentu.\n\nBekerja di gedung yang sama, memakai merek bersama, atau menggabungkan tim tidak dengan sendirinya menghasilkan penggabungan secara hukum. Tentukan dahulu tujuan dan pilih mekanisme berdasarkan keadaan masing-masing perseroan, bukan hanya istilah “digabung” dalam percakapan.', ['upt']),
      s('Baca dampak bagi pemilik dan pihak lain', 'Rancangan perlu memperhatikan keadaan keuangan, penilaian, serta konversi saham. Jika satu lembar saham pada PT asal ditukar dengan bagian tertentu pada PT penerima, hasilnya harus dihitung sampai tingkat pemegang saham. Pecahan tidak sebaiknya dibulatkan diam-diam karena dapat mengubah hak orang.\n\nUUPT mengatur perlindungan perseroan, pemegang saham minoritas, pekerja, kreditor, mitra usaha, dan persaingan usaha dalam tindakan korporasi ini. Kepemilikan oleh keluarga yang sama tidak menghapus kepentingan mereka. Periksa rancangan, pengumuman, pemberitahuan, keberatan kreditor, dan keputusan yang relevan sesuai ketentuan.', ['upt']),
      s('Rencanakan hari setelah penggabungan', 'Selain akta dan administrasi badan hukum, susun tindak lanjut atas rekening, perizinan, kontrak, pencatatan aset, dan hubungan kerja. Keberlanjutan suatu izin atau perlunya pembaruan tidak dapat diasumsikan sama untuk semua sektor. Aspek pajak dan kewajiban terkait persaingan usaha juga perlu diperiksa tersendiri.\n\nUntuk contoh dua perusahaan keluarga, langkah awal yang berguna adalah membuat dua inventaris yang terpisah sebelum menyusun gambaran gabungan. Dengan begitu, kewajiban perusahaan yang berhenti tidak hilang dari perhatian hanya karena kegiatan operasionalnya sudah dikerjakan oleh perusahaan penerima.')
    ], checklist: ['Dokumen korporasi, pemegang saham, dan laporan keuangan kedua PT.', 'Daftar aset, kewajiban, pekerja, izin, dan kontrak masing-masing.', 'Rencana perseroan penerima serta dasar penilaian dan konversi saham.'],
    takeaway: 'Pembahasan penggabungan dimulai dari dua keadaan perusahaan yang lengkap, bukan dari satu nama perusahaan yang ingin dipertahankan.',
    related: ['pembubaran-pt-dan-aset-tersisa', 'investor-baru-dilusi-saham'], repo: ['utils/penggabungan/konversiSaham.js', 'utils/penggabungan/kuorum.js']
  },
  {
    slug: 'sekutu-aktif-pasif-cv', type: 'CV', group: 'Memulai usaha', title: 'Sekutu aktif dan pasif CV: jangan hanya membedakan sebutan jabatan',
    intro: 'Siapa yang mengurus dan berhubungan dengan pihak ketiga mempunyai akibat terhadap kewenangan dan tanggung jawab.',
    scenario: 'Dua saudara mendirikan CV. Kakak disebut direktur dan adik disebut sekutu komanditer. Ketika kakak bepergian, adik menandatangani kontrak pembelian atas nama CV dengan surat kuasa. Mereka menganggap batas tanggung jawab adik tetap sama karena namanya di akta belum berubah.',
    sections: [
      s('Peran komanditer mempunyai batas', 'Pasal 19–21 KUHD membedakan kedudukan sekutu yang bertanggung jawab secara tanggung renteng dan sekutu komanditer. Sekutu komanditer tidak boleh melakukan tindakan pengurusan, termasuk dengan dasar pemberian kuasa sebagaimana diatur Pasal 20. Pelanggaran atas batas tersebut dapat berakibat pada tanggung jawabnya.\n\nKarena itu, menyebut seseorang “pasif” di dalam akta tidak cukup jika tindakannya justru merupakan pengurusan. Contoh penandatanganan kontrak perlu diperiksa dari kapasitas, isi dokumen, dan perbuatannya. Jangan menganggap surat kuasa selalu menjadi jalan aman untuk memindahkan tugas pengurus kepada sekutu komanditer.', ['dagang']),
      s('Atur kebutuhan informasi tanpa mencampur kewenangan', 'Sekutu yang menanamkan modal tentu memerlukan informasi mengenai usahanya. Mekanisme laporan, pembacaan buku, dan persetujuan yang diatur dalam perjanjian perlu dibedakan dari tindakan mengurus atau mewakili CV terhadap pihak ketiga. Rancang batas tersebut sesuai keadaan dan ketentuan hukum, bukan menyalin struktur organ PT.\n\nIstilah komisaris yang kadang digunakan dalam percakapan tidak dengan sendirinya membuat CV memiliki Dewan Komisaris dengan fungsi yang sama seperti PT. Bacalah akta untuk mengetahui peran sekutu sebenarnya. Perbedaan istilah dapat menjadi sumber salah paham ketika berurusan dengan pemasok atau bank.'),
      s('Jika pola kerjanya sudah berubah', 'Apabila kedua sekutu ternyata ingin sama-sama aktif mengurus, bicarakan penataan peran dan bentuk usaha yang sesuai. Perubahan susunan atau pengurus CV termasuk hal yang diatur dalam layanan perubahan menurut Permenkum 25/2025. Dokumen sebaiknya mengikuti pola kerja yang benar-benar dimaksudkan.\n\nUntuk transaksi yang sudah ditandatangani, jangan berasumsi perubahan akta kemudian otomatis menghapus akibat tindakan sebelumnya. Susun kronologi serta bukti tindakan dan minta penilaian sesuai kasus. Penataan ke depan dan pemeriksaan peristiwa yang sudah terjadi adalah dua pekerjaan yang berbeda.', ['cv'])
    ], checklist: ['Akta pendirian dan perubahan CV yang menjelaskan peran para sekutu.', 'Kontrak, surat kuasa, dan tindakan yang sudah dilakukan oleh masing-masing pihak.', 'Pola kerja yang diinginkan serta kebutuhan laporan kepada sekutu.'],
    takeaway: 'Saat membahas pendirian CV, ceritakan siapa yang akan bekerja dan menandatangani dokumen sehari-hari.',
    related: ['memilih-pt-atau-cv', 'sekutu-cv-masuk-keluar'], repo: ['docs/form-akta/FORM-pendirian-cv.md', 'utils/cv/pendirian.js']
  },
  {
    slug: 'sekutu-cv-masuk-keluar', type: 'CV', group: 'Mengembangkan usaha', title: 'Sekutu CV keluar dan pengganti masuk: apa yang perlu dibereskan?',
    intro: 'Perubahan nama sekutu perlu disertai kejelasan hak ekonomi, peran pengurus, dan hubungan dengan pihak ketiga.',
    scenario: 'Sekutu pengurus CV ingin berhenti dan digantikan rekannya. Ia meminta seluruh setoran dikembalikan pada hari penandatanganan perubahan. CV masih mempunyai tagihan pelanggan, utang pemasok, dan pembiayaan yang dahulu ditandatangani oleh sekutu tersebut.',
    sections: [
      s('Baca dasar pengunduran diri dan kelanjutan usaha', 'Periksa ketentuan dalam akta mengenai keluarnya sekutu, pemberitahuan, perhitungan hak, dan kelanjutan persekutuan. Jangan mengambil satu jangka waktu dari contoh akta lain lalu menganggapnya berlaku bagi seluruh CV. Perjanjian yang benar-benar mengikat para sekutu menjadi bahan pemeriksaan utama bersama ketentuan hukumnya.\n\nTentukan apakah CV dilanjutkan, siapa sekutu yang tetap, dan peran pihak yang masuk. Pergantian pengurus tidak selalu sama dengan pergantian seluruh sekutu. Dokumen harus membedakan orang yang keluar, orang yang masuk, serta susunan dan kewenangan setelah perubahan.', ['perdata', 'cv']),
      s('Setoran awal belum tentu sama dengan hak penyelesaian', 'Perhitungan dapat dipengaruhi oleh laba, rugi, pengambilan sebelumnya, aset, utang, dan kesepakatan para pihak. Mengembalikan angka setoran awal tanpa membaca keadaan usaha dapat merugikan salah satu pihak atau mengganggu kemampuan membayar kewajiban.\n\nPada contoh ini, buat tanggal batas perhitungan dan sepakati dokumen keuangan yang dipakai. Pisahkan pembayaran kepada sekutu lama dari pemasukan sekutu baru. Jika pembayaran dilakukan bertahap, tuliskan mekanisme serta konsekuensi yang disepakati secara jelas; jangan menyatakan seluruh hak telah diterima jika kenyataannya belum.'),
      s('Jangan lupakan pihak di luar persekutuan', 'Kesepakatan internal para sekutu tidak otomatis membebaskan pihak tertentu dari semua kewajiban kepada kreditor. Periksa kontrak pembiayaan, jaminan pribadi, dan syarat persetujuan atau pemberitahuan. Kewenangan menandatangani setelah perubahan juga perlu disampaikan kepada pihak yang relevan.\n\nPermenkum 25/2025 mengatur pendaftaran perubahan sekutu dan pengurus melalui Notaris. Pasal 10 menetapkan batas pengajuan perubahan anggaran dasar paling lama 30 hari kalender sejak akta ditandatangani. Rencanakan kelengkapan sebelum penandatanganan agar tindak lanjut tidak tertinggal.', ['cv', 'dagang'])
    ], checklist: ['Akta terakhir dan ketentuan pengunduran diri serta kelanjutan CV.', 'Perhitungan modal, laba-rugi, hak yang sudah diterima, serta kewajiban berjalan.', 'Dokumen pembiayaan, jaminan, dan rencana kewenangan pengurus pengganti.'],
    takeaway: 'Perubahan CV akan lebih jelas jika susunan orang dan penyelesaian hubungan ekonominya dibahas bersamaan.',
    related: ['sekutu-aktif-pasif-cv', 'sekutu-cv-meninggal'], repo: ['utils/cv/cvlib.js', 'utils/cv/suratPengunduran.js', 'utils/cv/cvValidator.js']
  },
  {
    slug: 'sekutu-cv-meninggal', type: 'CV', group: 'Menjaga kesinambungan', title: 'Sekutu CV meninggal: periksa kelanjutan usaha dan hak ahli waris',
    intro: 'Kelanjutan CV perlu dibaca dari perjanjian dan dasar kewarisan, bukan diasumsikan sama pada setiap persekutuan.',
    scenario: 'Sekutu pengurus sebuah CV meninggal dunia. Sekutu yang tersisa ingin melanjutkan pekerjaan dengan anak almarhum. Keluarga belum membahas dokumen kewarisan, sedangkan kontrak dengan pelanggan meminta kepastian siapa yang sekarang berwenang menandatangani.',
    sections: [
      s('Baca klausul kematian dan kelanjutan', 'Ketentuan persekutuan dalam KUHPerdata memuat persoalan berakhirnya persekutuan dan kesepakatan untuk melanjutkannya ketika seorang sekutu meninggal. Pasal 1651 menjadi salah satu rujukan untuk membaca kesepakatan kelanjutan dengan ahli waris atau sekutu yang masih ada. Isi akta CV yang bersangkutan perlu diperiksa secara utuh.\n\nJangan menyimpulkan semua CV otomatis berakhir tanpa melihat perjanjian, atau sebaliknya semua ahli waris otomatis menjadi pengurus. Klausul dalam satu contoh akta juga bukan aturan universal. Jangka waktu pemberitahuan, cara perhitungan hak, dan mekanisme kelanjutan dapat memerlukan pembahasan khusus.', ['perdata']),
      s('Pisahkan hak keluarga dari peran mengurus', 'Siapa yang berhak atas peninggalan almarhum harus didukung dasar kewarisan yang sesuai. Orang yang paling sering membantu usaha belum tentu menjadi satu-satunya ahli waris atau pihak yang berwenang mewakili semuanya. Jika digunakan kuasa, lingkup dan kapasitas pemberi serta penerimanya harus jelas.\n\nSelanjutnya tentukan apakah yang akan diselesaikan merupakan hak ekonomi ahli waris, masuknya sekutu baru, perubahan pengurus, atau beberapa peristiwa sekaligus. Menjadi ahli waris tidak dengan sendirinya sama dengan menyetujui peran sekutu aktif beserta tanggung jawabnya. Perbedaan peran aktif dan komanditer tetap perlu diterangkan.', ['dagang']),
      s('Jaga fakta dan tanggal dalam dokumen', 'Catat tanggal kematian berdasarkan dokumen sumber, bukan tanggal ketika akta perubahan dibuat. Susun keadaan CV pada saat peristiwa terjadi: aset, kewajiban, pekerjaan berjalan, dan sekutu yang masih dapat bertindak. Dengan demikian dokumen perubahan tidak memberi kesan orang yang telah meninggal masih mengambil keputusan baru.\n\nUntuk kelanjutan yang disepakati, periksa pendaftaran perubahan menurut Permenkum 25/2025 dan kebutuhan pembaruan kepada bank atau mitra. Jika belum ada kesepakatan keluarga atau dasar kewenangan, sampaikan bagian yang masih belum selesai secara terbuka sebelum menentukan jadwal penandatanganan.', ['cv'])
    ], checklist: ['Akta CV lengkap, terutama klausul kematian dan kelanjutan persekutuan.', 'Bukti kematian, dokumen kewarisan, dan kuasa jika ada.', 'Keadaan keuangan, pekerjaan berjalan, dan rencana sekutu atau pengurus setelahnya.'],
    takeaway: 'Pembahasan yang tertib menghubungkan keadaan keluarga dengan keberlanjutan usaha, tanpa menyamakan kedua urusan tersebut.',
    related: ['sekutu-cv-masuk-keluar', 'pemegang-saham-meninggal'], repo: ['utils/cv/cvValidator.js', 'docs/superpowers/specs/2026-08-05-gerbang-waris-pesero-cv-design.md']
  },
  {
    slug: 'usaha-cv-menjadi-pt', type: 'CV', group: 'Mengembangkan usaha', title: 'Usaha CV akan dilanjutkan lewat PT: jangan sekadar mengganti awalan nama',
    intro: 'Pendirian PT dan penataan usaha CV perlu dihubungkan melalui pemeriksaan aset, kontrak, kewajiban, serta perizinan.',
    scenario: 'CV yang menjalankan usaha interior mendapat calon investor yang menginginkan kepemilikan saham. Pemilik berencana mengganti “CV” menjadi “PT” pada penawaran berikutnya. Peralatan, piutang, sewa tempat, dan kontrak proyek masih terkait dengan usaha CV.',
    sections: [
      s('PT memerlukan dasar pendirian dan kepemilikannya sendiri', 'CV dan PT mempunyai struktur hukum yang berbeda. Rencana melanjutkan usaha melalui PT tidak cukup dilaksanakan dengan mengganti awalan nama pada dokumen. Tentukan pendiri, setoran modal, pembagian saham, pengurus, serta proses pendirian PT yang sesuai.\n\nFAQ AHU membahas pendirian PT dari usaha yang sebelumnya berbentuk CV dan perhatian terhadap pengambilalihan hak serta kewajiban tertentu. Gunakan pembahasan tersebut sebagai titik awal, bukan anggapan bahwa seluruh hubungan CV pasti berpindah hanya karena akta PT sudah ditandatangani. Ketentuan administrasi terkini tetap perlu dibaca bersama Permenkum 49/2025 dan 25/2025.', ['alihcv', 'pt', 'cv']),
      s('Petakan apa yang akan dialihkan', 'Buat daftar peralatan, persediaan, piutang, utang, merek, kontrak pelanggan, sewa, serta hubungan kerja. Untuk setiap item, tanyakan siapa pemilik atau pihak terikatnya, apa dokumen dasarnya, dan mekanisme apa yang diperlukan untuk pengalihan atau kelanjutannya. Beberapa hubungan dapat memerlukan persetujuan pihak lain.\n\nJika aset akan dipakai sebagai setoran modal PT, pembahasan penilaian dan penyerahannya berbeda dari sekadar menjual aset kepada PT. Jika ada pinjaman, periksa siapa debitornya dan apakah ada jaminan pribadi. Pajak serta biaya transaksi perlu dihitung sesuai mekanisme yang akhirnya dipilih.'),
      s('Tetapkan kapan setiap usaha mulai dan berhenti bertindak', 'Jadwal transisi membantu menentukan siapa yang menerbitkan penawaran, menagih pelanggan, menerima pembayaran, dan menanggung pekerjaan yang belum selesai. Hindari mencampur rekening dan identitas pada kontrak karena para pelaksananya masih orang yang sama.\n\nTentukan pula apakah CV dilanjutkan untuk kegiatan tertentu atau dibereskan melalui prosedur yang sesuai. Pendiriannya sebagai PT tidak otomatis menyelesaikan administrasi CV, perizinan, atau kewajiban lama. Rencana transisi yang jelas membuat investor dan mitra dapat memahami badan usaha mana yang menjadi pihak pada setiap tahap.', ['cv', 'izin'])
    ], checklist: ['Akta CV dan seluruh perubahan serta rencana pendiri dan pemegang saham PT.', 'Inventaris aset, kewajiban, kontrak, pekerja, serta izin yang akan ditata.', 'Jadwal peralihan kegiatan dan keputusan mengenai kelanjutan atau pemberesan CV.'],
    takeaway: 'Untuk membahas peralihan usaha, bawa gambaran transaksi dan kontrak berjalan selain rencana nama PT.',
    related: ['modal-dasar-ditempatkan-disetor', 'memilih-pt-atau-cv'], repo: ['utils/cv/generatorCv.js', 'docs/form-akta/FORM-pendirian-pt.md', 'docs/form-akta/FORM-pendirian-cv.md']
  }
);

articles.push(
  {
    slug: 'investor-baru-dilusi-saham', type: 'PT', group: 'Mengembangkan usaha', title: 'Investor baru masuk: uang bertambah, persentase pemilik berubah',
    intro: 'Penerbitan saham baru perlu dibaca dari nilai setoran, jumlah lembar, hak pemegang saham lama, dan perubahan pengendalian.',
    scenario: 'Dua pendiri memegang 600 dan 400 lembar saham. Investor ingin menyetor dana dengan imbalan 500 lembar baru. Pendiri pertama mengira ia tetap menguasai 60 persen karena jumlah saham miliknya tidak berkurang.',
    sections: [
      s('Jumlah tetap, persentase berubah', 'Sebelum transaksi terdapat 1.000 lembar. Sesudah penerbitan 500 lembar baru, totalnya 1.500. Pemilik 600 lembar menjadi pemilik 40 persen; pemilik 400 lembar sekitar 26,67 persen; investor sekitar 33,33 persen. Contoh ini mengasumsikan seluruh saham mempunyai hak yang sama dan tidak ada transaksi lain.\n\nPerubahan persentase seperti ini disebut dilusi. Dilusi tidak selalu buruk: modal tambahan dapat membantu usaha. Namun pemilik perlu memahami dampaknya terhadap pembagian keuntungan dan pengambilan keputusan. Gunakan jumlah lembar sebagai dasar perhitungan, lalu tampilkan persentase untuk membantu membaca hasilnya.'),
      s('Tawarkan dan putuskan melalui mekanisme yang tepat', 'Penambahan modal memerlukan keputusan yang sesuai. Pasal 41–43 UUPT mengatur penambahan modal dan penawaran saham baru kepada pemegang saham yang ada, dengan ketentuan serta pengecualian tertentu. Kesediaan seorang investor saja belum cukup untuk melewati hak pihak lain.\n\nPeriksa apakah modal dasar masih menampung saham yang akan diterbitkan, bagaimana hak pemegang saham lama dipenuhi, dan apakah ada klasifikasi saham dengan hak berbeda. Jika setoran investor melampaui nilai nominal saham, dasar pencatatan selisihnya perlu jelas. Nilai nominal, harga penerbitan, dan nilai perusahaan adalah angka yang berbeda.', ['upt']),
      s('Periksa siapa yang mengendalikan sesudahnya', 'Jangan berhenti pada tabel modal. Hak menunjuk pengurus, komposisi suara, dan perjanjian terkait dapat mempengaruhi kendali. UUPT menghubungkan pengambilalihan dengan beralihnya pengendalian. Angka persentase membantu membaca situasi, tetapi bukan satu-satunya pertanyaan hukum.\n\nPada contoh tersebut tidak ada pemegang saham tunggal yang memiliki lebih dari separuh. Itu belum menjawab seluruh persoalan kendali atau tata cara transaksi. Pembahasan dokumen perlu memeriksa hubungan para pihak, hak khusus, dan mekanisme perubahan secara utuh sebelum menyebutnya sekadar penambahan modal biasa.', ['upt'])
    ], checklist: ['Tabel pemegang saham sebelum dan sesudah, termasuk klasifikasi saham.', 'Nominal saham, harga penerbitan, jumlah setoran, dan bukti pemenuhan hak pemilik lama.', 'Perubahan hak suara, pengurus, dan perjanjian dengan investor.'],
    takeaway: 'Sebelum menyepakati angka investasi, pastikan semua pihak membaca tabel kepemilikan akhir yang sama.',
    related: ['modal-dasar-ditempatkan-disetor', 'jual-beli-saham-pengambilalihan'], repo: ['utils/sirkulerValidator.js', 'utils/pengambilalihan/pengendali.js']
  },
  {
    slug: 'jual-beli-saham-pengambilalihan', type: 'PT', group: 'Mengembangkan usaha', title: 'Jual beli saham atau pengambilalihan: lihat perubahan kendalinya',
    intro: 'Transaksi saham yang tampak serupa dapat memerlukan pembahasan berbeda ketika kendali perseroan berpindah.',
    scenario: 'Seorang pemegang saham dengan kepemilikan 30 persen hendak membeli 25 persen dari rekannya. Para pihak menyebutnya jual beli biasa karena penjual hanya melepas sebagian saham. Mereka belum membicarakan siapa yang akan menentukan susunan pengurus setelah transaksi.',
    sections: [
      s('Besarnya bagian yang dijual bukan satu-satunya ukuran', 'Dalam contoh ini pembeli akan memegang 55 persen. Perubahan tersebut perlu dinilai bersama hak suara, anggaran dasar, dan hubungan para pihak. Pasal 1 angka 11 dan Pasal 125 UUPT menghubungkan pengambilalihan dengan beralihnya pengendalian. Undang-undang tidak merumuskan setiap perpindahan di atas angka persentase tertentu sebagai jawaban tunggal untuk semua keadaan.\n\nKarena itu, pembahasan yang berhenti pada frasa “hanya menjual 25 persen” dapat melewatkan akibat penting. Sebaliknya, tidak setiap jual beli saham otomatis harus disebut pengambilalihan. Fakta sebelum dan sesudah transaksi menjadi titik awal penilaiannya.', ['upt']),
      s('Baca pembatasan dan jalur transaksinya', 'Anggaran dasar dapat memuat syarat pemindahan saham, seperti penawaran kepada pemegang saham lain atau persetujuan organ perseroan. Pasal 56–59 UUPT perlu dibaca bersama dokumen perseroan. Periksa juga apabila saham sedang dijaminkan atau terikat perjanjian lain.\n\nUntuk pengambilalihan, pembelian langsung dari pemegang saham mempunyai ketentuan yang perlu dibedakan dari pengambilalihan melalui Direksi. Jangan memakai satu daftar tahapan untuk seluruh transaksi tanpa memeriksa jalurnya. Kepentingan kreditor, pekerja, pemegang saham minoritas, dan pihak lain yang dilindungi hukum tetap perlu diperhatikan.', ['upt']),
      s('Setelah transaksi, rapikan bukti kepemilikan', 'Pembayaran harga bukan pengganti seluruh dokumen pemindahan. Siapkan dasar peralihan dan pastikan pencatatan serta pemberitahuan perubahan dilakukan sesuai ketentuan. Direksi juga perlu memelihara daftar pemegang saham. Akta transaksi dan daftar tersebut mempunyai fungsi yang saling melengkapi.\n\nBuat daftar tindak lanjut: pembaruan administrasi perseroan, data pengurus jika berubah, dan persetujuan atau pemberitahuan kepada mitra sesuai kontrak. Misalnya perjanjian kredit mungkin memuat klausul perubahan pengendalian. Penandatanganan akta tidak dengan sendirinya menghapus kewajiban kontraktual itu.', ['upt'])
    ], checklist: ['Akta dan anggaran dasar terbaru, daftar pemegang saham, serta dasar kepemilikan penjual.', 'Tabel komposisi sebelum dan sesudah serta hak khusus yang disepakati.', 'Perjanjian kredit, jaminan saham, dan pembatasan pemindahan yang relevan.'],
    takeaway: 'Jelaskan tujuan transaksi dan perubahan kendalinya sejak awal, agar bentuk akta dan tahapan yang dibahas sesuai peristiwanya.',
    related: ['investor-baru-dilusi-saham', 'saham-sama-rata-kebuntuan'], repo: ['utils/pengambilalihan/pengendali.js', 'utils/sahamLedger.js']
  },
  {
    slug: 'masa-jabatan-direksi-komisaris', type: 'PT', group: 'Menata keputusan', title: 'Masa jabatan pengurus berakhir saat kontrak baru akan ditandatangani',
    intro: 'Nama yang masih tercantum dalam data perseroan belum cukup untuk memastikan kewenangan seseorang pada tanggal transaksi.',
    scenario: 'Sebuah PT akan menandatangani kontrak pemasok. Direktur yang biasa mewakili perseroan masih tercantum pada dokumen yang dipakai staf. Saat riwayat akta dibaca, masa jabatan pengangkatannya ternyata telah lewat. Para pemilik mengira pengangkatan otomatis berlanjut selama belum ada pengganti.',
    sections: [
      s('Mulai dari keputusan pengangkatan dan anggaran dasar', 'Pasal 94 UUPT mengatur pengangkatan anggota Direksi oleh RUPS untuk jangka waktu tertentu dan kemungkinan pengangkatan kembali. Ketentuan mengenai Dewan Komisaris antara lain terdapat dalam Pasal 111. Periksa bunyi keputusan, tanggal mulai berlaku, lama jabatan, serta ketentuan penggantian atau pengunduran diri.\n\nData yang tampil pada suatu profil administrasi perlu dibandingkan dengan dasar hukumnya. Tidak tepat menganggap jabatan selalu diperpanjang otomatis karena nama belum berubah. Sebaliknya, akibat terhadap kontrak tertentu juga tidak boleh diputus hanya dari satu tanggal tanpa membaca keseluruhan dokumen.', ['upt']),
      s('Pisahkan pengangkatan kembali dari perubahan kepemilikan', 'Pemegang saham dapat tetap sama ketika Direksi atau Komisaris berganti. Demikian pula penjualan saham tidak otomatis mengangkat pembeli menjadi direktur. Jika kedua peristiwa terjadi bersama, masing-masing perlu memiliki keputusan, tanggal efektif, dan dokumentasi yang jelas.\n\nSusun kronologi sebelum menyiapkan keputusan. Apakah masa jabatan sudah berakhir, apakah ada pengunduran diri, dan siapa yang berwenang melakukan tindakan sementara menurut anggaran dasar? Jangan membuat tanggal keputusan mundur untuk menutupi keterlambatan. Dokumen harus menerangkan peristiwa yang benar-benar terjadi.'),
      s('Sesuaikan jadwal transaksi dan pembaruan administrasi', 'Setelah keputusan yang sah, tindak lanjut dapat mencakup pemberitahuan perubahan data perseroan dan pembaruan spesimen atau kewenangan pada bank serta mitra. Permenkum 49/2025 mengatur layanan perubahan perseroan; daftar dokumen dan waktu pengajuan perlu disesuaikan dengan peristiwa yang dilakukan.\n\nUntuk kontrak yang sudah mendesak, mintalah pemeriksaan kewenangan sebelum menentukan penandatangan. Jangan berasumsi surat kuasa selalu menyelesaikan masalah jika pemberi kuasanya sendiri dipertanyakan kewenangannya. Pengaturan kalender jabatan dan arsip keputusan dapat membantu mencegah persoalan serupa pada transaksi berikutnya.', ['pt'])
    ], checklist: ['Akta pengangkatan terakhir dan seluruh keputusan yang mempengaruhi jabatan.', 'Pasal anggaran dasar mengenai masa jabatan dan perwakilan perseroan.', 'Tanggal kontrak yang direncanakan serta dokumen kewenangan yang diminta mitra.'],
    takeaway: 'Pemeriksaan kewenangan lebih baik dilakukan sebelum jadwal tanda tangan ditetapkan.',
    related: ['rups-dan-keputusan-sirkuler', 'laporan-tahunan-pt'], repo: ['utils/sirkulerValidator.js', 'docs/form-akta/FORM-pkps-sirkuler.md']
  },
  {
    slug: 'rups-dan-keputusan-sirkuler', type: 'PT', group: 'Menata keputusan', title: 'RUPS atau keputusan sirkuler: pilih dari cara persetujuannya',
    intro: 'Keputusan di luar rapat memerlukan persetujuan seluruh pemegang saham dengan hak suara, bukan hanya mayoritas.',
    scenario: 'Empat pemegang saham berada di kota berbeda. Tiga orang yang menguasai 90 persen saham setuju mengganti direktur. Seorang pemegang saham dengan 10 persen belum menjawab. Mereka ingin menandatangani keputusan sirkuler agar tidak perlu mengadakan rapat.',
    sections: [
      s('Diam bukan tanda tangan persetujuan', 'Pasal 91 UUPT memungkinkan keputusan yang mengikat di luar RUPS apabila seluruh pemegang saham dengan hak suara menyetujui secara tertulis dengan menandatangani usul yang bersangkutan. Dalam contoh tersebut, persetujuan 90 persen belum memenuhi syarat keputusan sirkuler.\n\nPesan bahwa seseorang “tidak keberatan” juga perlu dibedakan dari bukti persetujuan tertulis terhadap rumusan keputusan yang akan dipakai. Pastikan setiap pihak menyetujui teks yang sama. Jika ada perubahan materi setelah sebagian pihak menandatangani, proses persetujuannya perlu diperiksa kembali.', ['upt']),
      s('Rapat mempunyai jalur dan syarat tersendiri', 'Apabila persetujuan bulat tidak tersedia, pertimbangkan mekanisme RUPS yang sesuai. Periksa pemanggilan, agenda, peserta yang berhak, kuorum kehadiran, dan jumlah suara setuju. Ambang keputusan dapat berbeda menurut jenis agenda serta anggaran dasar; angka untuk keputusan biasa tidak selalu dapat dipakai untuk perubahan anggaran dasar atau tindakan korporasi tertentu.\n\nUUPT juga mengenal RUPS melalui media elektronik dengan syaratnya. Rapat jarak jauh tetap merupakan rapat dan perlu memenuhi ketentuan penyelenggaraan serta risalahnya. Keputusan sirkuler adalah cara yang berbeda, sehingga jangan mencampur dokumentasinya hanya karena keduanya tidak mengharuskan semua orang duduk di ruangan yang sama.', ['upt']),
      s('Tentukan apa yang akan dituangkan dalam akta', 'Jika Notaris hadir dan membuat berita acara rapat, dasar pencatatannya berbeda dari penghadap yang kemudian menyatakan keputusan yang telah diambil. Dokumen pendukung, kapasitas penghadap, dan kuasa untuk menyatakan keputusan perlu sesuai dengan peristiwa sebenarnya.\n\nUntuk pemberhentian pengurus, jangan hanya memeriksa suara pemegang saham. UUPT juga mengatur kesempatan membela diri dalam pemberhentian Direksi, dengan ketentuan dan pengecualian yang perlu dibaca sesuai keadaan. Memilih bentuk keputusan yang ringkas tidak menghapus perlindungan prosedural tersebut.', ['upt'])
    ], checklist: ['Daftar pemegang saham dan hak suara pada saat keputusan diambil.', 'Rumusan agenda, draf keputusan, dan bukti persetujuan atau pemanggilan rapat.', 'Anggaran dasar serta dasar kuasa penghadap jika keputusan akan dinyatakan dalam akta.'],
    takeaway: 'Tentukan cara mengambil keputusan sebelum menyiapkan nama dan bentuk aktanya.',
    related: ['saham-sama-rata-kebuntuan', 'masa-jabatan-direksi-komisaris'], repo: ['utils/sirkulerValidator.js', 'utils/penggabungan/kuorum.js', 'docs/peta-generator.md']
  },
  {
    slug: 'laporan-tahunan-pt', type: 'PT', group: 'Menata keputusan', title: 'PT belum aktif: apakah laporan tahunan tetap perlu dibahas?',
    intro: 'Tidak ada penjualan bukan berarti tidak ada keadaan perseroan yang perlu dilaporkan dan dipertanggungjawabkan.',
    scenario: 'PT yang baru didirikan belum memperoleh proyek sampai akhir tahun buku. Pemilik menganggap laporan tahunan belum diperlukan. Padahal perseroan sudah menerima setoran modal, membayar sewa, dan membeli peralatan. Komisaris belum menerima ringkasan kegiatan maupun posisi keuangannya.',
    sections: [
      s('Laporan menjelaskan keadaan usaha, termasuk ketika belum berjalan', 'Pasal 66 UUPT mengatur penyampaian laporan tahunan oleh Direksi kepada RUPS setelah ditelaah Dewan Komisaris. RUPS tahunan diatur dalam Pasal 78, dengan batas paling lambat enam bulan setelah tahun buku berakhir. Laporan tidak hanya berisi angka penjualan; modal, aset, biaya, kewajiban, dan kegiatan pengawasan juga relevan.\n\nJika suatu pos memang nihil, tuliskan berdasarkan pemeriksaan dan catatan yang mendukungnya. Dalam contoh tersebut, menyatakan seluruh kegiatan dan keuangan nihil justru tidak menggambarkan setoran, sewa, serta pembelian peralatan yang sudah terjadi.', ['upt']),
      s('Perhatikan ketentuan penyampaian yang lebih baru', 'Untuk perseroan persekutuan modal, Pasal 16 Permenkum 49/2025 mengatur bahwa persetujuan RUPS atas laporan tahunan dimuat dalam akta notaris dan disampaikan kepada Menteri oleh Direksi melalui Notaris, paling lama 30 hari kalender sejak akta ditandatangani. Ketentuan itu juga mengatur pengunggahan dokumen pendukung melalui SABH.\n\nKarena itu, kalender tahunan perlu memisahkan penyusunan laporan, penelaahan Komisaris, keputusan RUPS, akta, dan penyampaiannya. Jalur laporan keuangan perseroan perorangan diatur tersendiri; jangan memakai alur PT persekutuan modal tanpa memeriksa bentuk perseroannya.', ['pt']),
      s('Angka yang rapi memudahkan keputusan yang tepat', 'Cocokkan laporan keuangan dengan perubahan modal, utang kepada pemegang saham, transaksi aset, dan keputusan sepanjang tahun. Periksa pula apakah perseroan termasuk yang wajib diaudit menurut Pasal 68 UUPT atau ketentuan lain yang berlaku. Status sebagai perusahaan tertutup atau usaha kecil saja tidak menjawab semua kategori kewajiban audit.\n\nPersetujuan laporan dan keputusan penggunaan laba harus dibaca terpisah. Rapat dapat membahas keadaan perusahaan tanpa memutus pembagian dividen. Jika dokumen tahun sebelumnya belum tertib, susun kronologi dan kekurangannya secara terbuka; jangan mengubah tanggal atau mengarang laporan agar tampak lengkap.', ['upt'])
    ], checklist: ['Laporan keuangan, ringkasan kegiatan, dan laporan pengawasan Komisaris.', 'Riwayat modal, pengurus, serta keputusan penting selama tahun buku.', 'Jadwal penelaahan, RUPS, akta, dan penyampaian laporan sesuai aturan yang berlaku.'],
    takeaway: 'Penataan laporan sejak awal tahun memberi ruang untuk memeriksa substansi sebelum tenggat keputusan dan penyampaian.',
    related: ['dividen-saldo-laba-cadangan', 'masa-jabatan-direksi-komisaris'], repo: ['utils/sirkulerValidator.js', 'docs/peta-generator.md']
  }
);

articles.push(
  {
    slug: 'dividen-saldo-laba-cadangan', type: 'PT', group: 'Menata keputusan', title: 'Kas tersedia, tetapi apakah PT sudah dapat membagikan dividen?',
    intro: 'Saldo bank, laba tahun berjalan, dan saldo laba adalah ukuran berbeda. Keputusan dividen perlu membaca ketiganya dengan tepat.',
    scenario: 'PT memiliki uang Rp500 juta di rekening. Sebagian berasal dari pinjaman bank. Tahun ini perusahaan mencatat laba, tetapi masih membawa rugi tahun sebelumnya. Para pemilik ingin membagikan sebagian kas sebelum membahas laporan keuangan lengkap.',
    sections: [
      s('Uang di rekening bukan seluruhnya laba', 'Kas dapat berasal dari penjualan, setoran modal, pinjaman, atau pembayaran pelanggan untuk pekerjaan yang belum selesai. Karena itu, saldo rekening tidak dapat langsung dipakai sebagai angka dividen. Laporan keuangan perlu menunjukkan sumber dana, kewajiban, serta saldo laba yang relevan.\n\nPasal 71 UUPT mengatur penggunaan laba melalui keputusan RUPS dan mensyaratkan saldo laba positif untuk pembagian dividen. Laba tahun berjalan perlu dibaca bersama akumulasi hasil tahun sebelumnya. Jika laba tahun ini Rp100 juta tetapi rugi yang masih diperhitungkan Rp150 juta, angka tahun berjalan saja belum mendukung kesimpulan bahwa tersedia saldo laba positif.', ['upt']),
      s('Penyisihan cadangan juga perlu dihitung', 'Pasal 70 UUPT mengatur penyisihan laba bersih untuk cadangan dengan ketentuan saldo laba positif, sampai cadangan mencapai paling sedikit 20 persen dari modal ditempatkan dan disetor. Ini bukan pernyataan bahwa setiap tahun selalu wajib menyisihkan 20 persen dari laba tahunan. Besaran penyisihan perlu dibaca bersama keadaan cadangan dan keputusan penggunaan laba.\n\nSesudah aspek hukum dan akuntansi diperiksa, pertimbangkan kebutuhan kas usaha, pembayaran utang, dan pembatasan dalam perjanjian pembiayaan. Keputusan yang memenuhi satu syarat belum tentu menyelesaikan seluruh persoalan likuiditas dan kontrak perseroan.', ['upt']),
      s('Tuliskan keputusan sesuai aliran dananya', 'Tentukan jumlah dividen, pihak yang berhak, dasar pembagiannya, dan cara pembayaran. Jika pemilik ingin menyetorkannya kembali sebagai modal, keputusan penggunaan laba dan keputusan penambahan modal perlu konsisten. Jangan menganggap label “dividen jadi modal” sudah cukup untuk menjelaskan seluruh mekanisme.\n\nPerlakuan pajak bergantung pada penerima dan pelaksanaan transaksi sehingga perlu diperiksa tersendiri; artikel ini tidak menetapkan tarif atau fasilitas pajak. Untuk pembagian sebelum akhir tahun buku, periksa ketentuan dividen interim dalam Pasal 72, bukan langsung menggunakan alur dividen tahunan.', ['upt'])
    ], checklist: ['Laporan keuangan yang menunjukkan laba, rugi terdahulu, cadangan, dan kewajiban.', 'Modal ditempatkan dan disetor serta daftar pihak yang berhak atas dividen.', 'Rencana pembayaran dan kebutuhan kas setelah pembagian.'],
    takeaway: 'Pembicaraan dividen sebaiknya dimulai dari laporan keuangan yang dapat dijelaskan, bukan dari jumlah uang yang ingin diambil pemilik.',
    related: ['laporan-tahunan-pt', 'modal-dasar-ditempatkan-disetor'], repo: ['utils/sirkulerValidator.js', 'docs/superpowers/specs/2026-08-15-dividen-setor-modal-design.md']
  },
  {
    slug: 'pemegang-saham-meninggal', type: 'PT', group: 'Menjaga kesinambungan', title: 'Pemegang saham meninggal: menata bukti waris dan hak dalam PT',
    intro: 'Kedudukan sebagai ahli waris, pencatatan saham, dan jabatan pengurus perlu diperiksa secara terpisah.',
    scenario: 'Pemilik 40 persen saham meninggal dunia dan meninggalkan beberapa anggota keluarga. Salah seorang anak yang selama ini membantu usaha ingin langsung menandatangani keputusan pemegang saham menggantikan orang tuanya. Daftar pemegang saham belum diperbarui dan dokumen kewarisan belum dibahas.',
    sections: [
      s('Mulai dari hak yang dapat dibuktikan', 'Keterlibatan sehari-hari dalam usaha tidak otomatis membuktikan bahwa seseorang menjadi satu-satunya pihak yang berhak atas saham pewaris. Perlu ditentukan dahulu kepemilikan saham yang termasuk harta peninggalan, dasar kewarisan yang berlaku, serta pihak-pihak yang berhak. Keadaan perkawinan, wasiat, dan dokumen lain dapat mempengaruhi pembahasannya.\n\nArtikel ini tidak menentukan bagian waris atau memilih sistem hukum waris untuk keluarga tertentu. Tujuannya menempatkan pemeriksaan kewarisan sebelum membuat pernyataan kepemilikan dalam keputusan perseroan. Keputusan yang ditandatangani dengan kapasitas yang belum jelas dapat menimbulkan persoalan pada tahap berikutnya.'),
      s('Baca aturan saham dan perwakilan bersama', 'UUPT mengatur pencatatan pemegang saham serta pelaksanaan hak atas saham. Pasal 52 mengatur saham yang dimiliki lebih dari satu orang dan penunjukan seorang wakil bersama untuk menggunakan hak yang timbul dari saham tersebut. Kebutuhan perwakilan tidak sama dengan penetapan bahwa wakil tersebut memiliki seluruh saham untuk dirinya sendiri.\n\nPemindahan karena kewarisan juga perlu dibedakan dari jual beli. Periksa ketentuan anggaran dasar dan Pasal 57 UUPT, termasuk aturan yang berkaitan dengan kewarisan dan persetujuan instansi yang berwenang. Jangan menerapkan semua syarat penjualan saham secara otomatis atau menganggap seluruh ketentuan dapat diabaikan.', ['upt']),
      s('Jika pewaris juga merupakan direktur', 'Berakhirnya peran pengurus dan beralihnya hak atas saham merupakan dua persoalan berbeda. Menjadi ahli waris tidak otomatis berarti menjadi direktur. Susunan pengurus dan kewenangan penandatanganan operasional perlu ditata melalui mekanisme perseroan yang sesuai.\n\nSusun urutan dokumen: bukti kematian, dasar kewarisan, bukti kepemilikan saham, keputusan yang diperlukan, dan pencatatan perubahan. Bagi usaha keluarga, arsip yang rapi membantu pembicaraan tetap berfokus pada hak dan kelangsungan usaha tanpa mengandalkan ingatan satu orang.', ['upt', 'pt'])
    ], checklist: ['Bukti kematian dan dokumen kewarisan yang tersedia.', 'Daftar pemegang saham, bukti kepemilikan, dan anggaran dasar terbaru.', 'Keterangan jabatan pewaris dan transaksi atau keputusan yang sedang menunggu.'],
    takeaway: 'Bawalah riwayat kepemilikan dan keadaan keluarga secara utuh. Hak waris serta kewenangan dalam perusahaan perlu dihubungkan dengan dasar yang jelas.',
    related: ['masa-jabatan-direksi-komisaris', 'jual-beli-saham-pengambilalihan'], repo: ['utils/sahamLedger.js', 'docs/superpowers/specs/2026-08-02-administrasi-saham-design.md']
  },
  {
    slug: 'menambah-kegiatan-usaha-kbli', type: 'PT & CV', group: 'Mengembangkan usaha', title: 'Usaha bertambah: selaraskan kegiatan, anggaran dasar, dan KBLI',
    intro: 'Menambah kode tidak sama dengan memperoleh seluruh izin. Mulailah dari kegiatan yang benar-benar akan dijalankan.',
    scenario: 'Perusahaan perdagangan mulai menerima pesanan produksi barang dengan merek sendiri. Pemilik ingin menambah semua kode yang terlihat berdekatan agar tidak perlu mengubah dokumen lagi. Kegiatan pabrik, tempat produksi, dan siapa yang melakukan prosesnya belum dijelaskan.',
    sections: [
      s('Ceritakan alur kerja sebelum memilih kode', 'Bedakan membeli barang jadi untuk dijual kembali, memproduksi sendiri, atau menggunakan produsen lain. Uraian barang, proses, pelanggan, lokasi, serta pihak yang menjalankan kegiatan membantu menentukan klasifikasi yang relevan. Nama usaha di media sosial belum tentu menggambarkan kegiatan hukumnya secara lengkap.\n\nMenambahkan banyak kode tanpa rencana dapat membuat pemeriksaan izin menjadi tidak terarah. Setiap kegiatan perlu dicocokkan dengan ruang lingkup anggaran dasar dan ketentuan sektor yang berlaku. Untuk PT, perubahan maksud, tujuan, dan kegiatan usaha terkait dengan perubahan anggaran dasar; CV juga mempunyai mekanisme perubahan kegiatan usaha dalam administrasinya.', ['upt', 'cv']),
      s('Bedakan perubahan kegiatan dari penyesuaian klasifikasi', 'KBLI 2025 telah diterbitkan. BPS dalam penjelasan resmi 27 April 2026 menyatakan bahwa implementasinya tidak mewajibkan pelaku usaha mengurus perizinan baru semata-mata karena perubahan klasifikasi, dan penyesuaian dilakukan menurut mekanisme yang ditetapkan. Informasi tersebut tidak berarti penambahan kegiatan nyata bebas dari pemeriksaan izin.\n\nKarena kode dan uraian dapat berubah, periksa tabel kesesuaian serta data yang tampil pada sistem ketika perubahan diajukan. Jangan sekadar mengganti angka lama dengan angka yang mirip. Pisahkan kegiatan yang tetap, kegiatan yang benar-benar baru, dan perubahan penamaan atau pengelompokan.', ['kbli']),
      s('Tutup pembahasan dengan daftar tindak lanjut', 'PP 28/2025 menjadi rujukan perizinan berusaha berbasis risiko. Kebutuhan perizinan dan pemenuhan standar perlu dilihat menurut kegiatan serta kondisi usaha. Akta perubahan tidak otomatis mengaktifkan seluruh izin operasional atau menggantikan persyaratan lokasi.\n\nUntuk contoh produksi tadi, susun dahulu fakta tempat dan proses produksi serta kerja sama dengan pihak lain. Setelah klasifikasi dan ruang lingkup perubahan jelas, barulah tahapan akta, administrasi badan usaha, dan perizinan dapat dibicarakan secara berurutan. Simpan bukti pembaruan agar data antardokumen tetap dapat dibandingkan.', ['izin'])
    ], checklist: ['Uraian kegiatan sekarang dan kegiatan baru, termasuk siapa pelaksana serta lokasinya.', 'Akta terakhir, data AHU, NIB, dan izin atau sertifikat standar yang dimiliki.', 'Daftar kode lama beserta uraian lengkapnya, bukan hanya angka.'],
    takeaway: 'Uraian kegiatan yang konkret lebih membantu daripada daftar kode yang panjang.',
    related: ['pindah-alamat-kedudukan-pt', 'memilih-pt-atau-cv'], repo: ['utils/cv/kbliKurasi.js', 'utils/sirkulerValidator.js', 'docs/form-akta/FORM-pendirian-pt.md']
  },
  {
    slug: 'pindah-alamat-kedudukan-pt', type: 'PT', group: 'Mengembangkan usaha', title: 'PT pindah kantor: perubahan alamat atau perubahan kedudukan?',
    intro: 'Pindah ke jalan lain dalam kota yang sama berbeda dari perpindahan tempat kedudukan ke kota atau kabupaten lain.',
    scenario: 'PT berkedudukan di Kota Cimahi berencana menyewa kantor di Kota Bandung. Staf ingin cukup mengganti alamat pada kop surat dan data pelanggan. Pemilik belum memastikan apakah tempat kedudukan perseroan ikut dipindahkan atau hanya membuka lokasi kegiatan tambahan.',
    sections: [
      s('Baca dua lapis identitas lokasi', 'UUPT membedakan tempat kedudukan yang ditentukan dalam anggaran dasar dan alamat lengkap perseroan. Pasal 21 memasukkan perubahan nama dan/atau tempat kedudukan dalam perubahan anggaran dasar yang memerlukan persetujuan Menteri. Oleh karena itu perpindahan kedudukan tidak cukup diperlakukan sebagai suntingan alamat korespondensi.\n\nPindah alamat di dalam wilayah kedudukan yang sama juga tetap memerlukan penataan data yang relevan, tetapi jangan disamakan begitu saja dengan perubahan kedudukan. Bacalah bunyi anggaran dasar dan rencana penggunaan lokasi baru sebelum menentukan jalur administrasinya.', ['upt', 'pt']),
      s('Pastikan tujuan penggunaan lokasi baru', 'Apakah kantor baru menjadi pusat perseroan, cabang, gudang, ruang produksi, atau sekadar tempat rapat? Satu alamat sewa tidak dengan sendirinya menjawab pertanyaan tersebut. Periksa pula kesesuaian penggunaan lokasi dan persyaratan izin untuk kegiatan yang akan dilakukan di sana.\n\nPada contoh Cimahi–Bandung, pemilik perlu memutuskan apakah benar mengubah kedudukan atau mempertahankannya sambil menambah lokasi kegiatan. Keputusan harus menggambarkan keadaan yang akan dijalankan. Jangan mempertahankan suatu alamat pada dokumen jika tidak ada lagi dasar penggunaan atau keadaan sebenarnya yang mendukungnya.', ['izin']),
      s('Perubahan tidak berhenti pada kop surat', 'Setelah keputusan dan administrasi yang diperlukan, susun daftar pihak serta sistem yang menggunakan alamat: data badan hukum, perizinan, perpajakan, bank, pemberi pembiayaan, dan kontrak utama. Kewajiban memperbarui atau memberitahu perlu dibaca sesuai aturan serta perjanjian masing-masing.\n\nGunakan satu tanggal dan kronologi yang konsisten untuk menjelaskan perpindahan. Simpan dokumen sewa atau penggunaan tempat dan bukti pembaruan. Untuk transaksi yang sedang berlangsung, konfirmasikan kepada mitra dokumen lokasi mana yang mereka perlukan agar alamat lama dan baru tidak menimbulkan kebingungan saat tanda tangan.')
    ], checklist: ['Anggaran dasar yang menyebut kedudukan serta alamat yang saat ini terdaftar.', 'Alamat baru dan fungsi setiap lokasi usaha.', 'Dasar penggunaan tempat, daftar izin, dan kontrak yang mensyaratkan pemberitahuan.'],
    takeaway: 'Sampaikan kota atau kabupaten lama dan baru secara lengkap, bukan hanya nama jalan, saat membahas perubahan.',
    related: ['menambah-kegiatan-usaha-kbli', 'rups-dan-keputusan-sirkuler'], repo: ['utils/sirkulerValidator.js', 'utils/sirkulerKlausul.js']
  },
  {
    slug: 'pembubaran-pt-dan-aset-tersisa', type: 'PT', group: 'Menjaga kesinambungan', title: 'PT berhenti berusaha, tetapi masih memiliki aset dan tagihan',
    intro: 'Menghentikan kegiatan, memutus pembubaran, dan menyelesaikan likuidasi adalah tahap yang perlu dibedakan.',
    scenario: 'Sebuah PT tidak lagi menerima pesanan. Pemilik menganggap perseroan dapat ditutup dengan satu keputusan. Setelah diperiksa, masih ada piutang pelanggan, merek yang terdaftar atas nama PT, utang pemasok, dan uang jaminan sewa yang belum dikembalikan.',
    sections: [
      s('Tidak beroperasi bukan berarti tidak ada yang dibereskan', 'Daftar aset perlu meliputi uang, barang, piutang, dan hak tidak berwujud yang benar-benar dimiliki perseroan. Daftar kewajiban perlu mencakup utang, kontrak berjalan, serta hak pihak lain yang masih harus dituntaskan. Menulis “nihil” hanya karena kantor sudah tutup dapat menghilangkan persoalan dari dokumen tanpa menyelesaikannya.\n\nPada pembubaran sukarela, UUPT mengatur likuidasi dan tugas likuidator. Pasal 143 menegaskan bahwa pembubaran tidak langsung menghilangkan status badan hukum sebelum likuidasi selesai dan pertanggungjawaban likuidator diterima sesuai ketentuan. Jadi ada pekerjaan setelah keputusan pembubaran.', ['upt']),
      s('Susun urutan pemberesan, bukan langsung pembagian', 'Dalam contoh tersebut, penagihan piutang, penyelesaian utang, dan penataan hak atas merek perlu masuk dalam inventarisasi. Aset perseroan tidak otomatis menjadi milik pribadi pemegang saham pada hari usaha berhenti. Pengalihan atau pembagiannya perlu mempunyai dasar dan memperhatikan kewajiban kepada kreditor.\n\nPengumuman, pemberitahuan, pengajuan tagihan, serta pertanggungjawaban bukan formalitas yang dapat diabaikan karena para pemilik sudah sepakat. Rencana waktu harus mempertimbangkan tahapan perlindungan pihak lain. Jika harta tidak cukup membayar kewajiban, keadaan itu membutuhkan penilaian tersendiri, bukan sekadar menghapus utang dari daftar.', ['upt']),
      s('Jika aset baru diketahui belakangan', 'Jangan langsung menggunakan nama bekas pemilik untuk menjual aset yang masih tercatat atas nama perseroan. Periksa dahulu status badan hukum, dokumen pembubaran, pelaksanaan likuidasi, dan kewenangan pihak yang akan bertindak. Tahapan yang tepat bergantung pada kapan serta dalam keadaan apa aset tersebut ditemukan.\n\nPembahasan dengan Notaris akan lebih berguna jika disertai inventaris dan kronologi. Dokumen penutupan yang tertib harus mengikuti keadaan nyata perseroan, termasuk persoalan yang belum selesai, bukan sekadar memenuhi keinginan agar nama perusahaan segera tidak digunakan lagi.', ['pt'])
    ], checklist: ['Akta, data perseroan, dan dasar rencana pembubaran.', 'Daftar aset berwujud dan tidak berwujud, piutang, utang, serta kontrak.', 'Dokumen pengumuman, tagihan, dan pekerjaan likuidator jika proses sudah dimulai.'],
    takeaway: 'Sebelum meminta akta pembubaran, petakan apa yang masih dimiliki dan masih menjadi kewajiban perseroan.',
    related: ['penggabungan-dua-pt', 'laporan-tahunan-pt'], repo: ['utils/pembubaran/validasi.js', 'utils/pembubaran/timeline/tahapan.js']
  }
);
